@extends('layouts.structure')
@push('title')
    <title>Purchase Order Details</title>
@endpush
@push('css')
@endpush
@section('main-content')
<div class="row">
    <div class="card">
        <div class="card-header d-block card_hearder_mimi">
            <div class="row">
                <div class="col-md-6 card-title card_hearder_mimi_text">
                    Purchase Order Details
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="col-md-12" style="float: left;">
                <div class="row">
                    <div class="col-md-4">
                        <span class="requisition_header"><i class="fas fa-yin-yang text-danger"></i> Purchase Order No : </span><span
                            class="requisition_text">PO#{{@$data->id}}
                        </span>
                    </div>
                    <div class="col-md-4">
                        <span class="requisition_header"><i class="fas fa-yin-yang text-danger"></i> Purchase Order Date : </span><span
                            class="requisition_text">
                            {{dateFor($data->po_date, true)}}
                        </span>
                    </div>
                    <div class="col-md-4">
                        <span class="requisition_header"><i class="fas fa-yin-yang text-danger"></i> Generated By : </span><span
                            class="requisition_text">{{@$data->created_by}}
                        </span>
                    </div>
                    <div class="col-md-4">
                        <span class="requisition_header"><i class="fas fa-yin-yang text-danger"></i> Note : </span><span class="requisition_text"
                            style="color:blue">{{@$data->note}}
                        </span>
                    </div>
                    <div class="col-md-4">
                        <span class="requisition_header"><i class="fas fa-yin-yang text-danger"></i> Vendor : </span><span class="requisition_text"
                            style="color:blue"> {{@$data->vendor }}
                        </span>
                    </div>
                    {{-- <div class="col-md-4">
                        {!! @$data->is_given == '0' ? '<span style="color :#c01e1e ;font-size: 18px; font-weight: 600;">Not issued</span>':'<span style="color:#158f34;font-size: 18px; font-weight: 600;">Issued</span>' !!}
                    </div> --}}
                </div>

            </div>
            <div class="table-responsive mt-4">
                <table class="table table-striped card-table table-vcenter text-nowrap border">
                    <thead class="bg-primary text-white">
                        <tr class="border">
                            <th  class="text-white border">#</th>
                            <th  class="text-white border">Item Name</th>
                            <th  class="text-white border">Unit Quantity</th>
                            <th  class="text-white border">Unit Name</th>
                            <th  class="text-white border">Sub Unit Quantity</th>
                            <th  class="text-white border">Sub Unit Name</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if(isset($item_list) && $item_list != '')
                        @foreach($item_list as $list)
                        <tr>
                            <th scope="row" class="border">{{ $loop->iteration }}</th>
                            <td class="border">{{$list->item_name}} </td>
                            <td class="border">{{$list->unit_qty}} </td>
                            <td class="border">{{$list->unit_name}} </td>
                            <td class="border">{{$list->sub_unit_qty}} </td>
                            <td class="border">{{$list->sub_unit_name}} </td>
                        </tr>
                        @endforeach
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js')
@endpush

