@extends('layouts.structure')
@push('title')
    <title>Purchase Details</title>
@endpush
@push('css')
@endpush
@section('main-content')
<div class="row">
    <div class="card">
        <div class="card-header d-block card_hearder_mimi">
            <div class="row">
                <div class="col-md-6 card-title card_hearder_mimi_text">
                    Purchase Details
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-3">
                    <span class="requisition_header">Purchase No. : </span><span class="requisition_text">P#{{ @$data->id }}</span>
                </div>
                <div class="col-md-3">
                    <span class="requisition_header">Purchase Date : </span><span class="requisition_text"><?= date('d-m-Y h:i A', strtotime(@$data->date)); ?></span>
                </div>
                <div class="col-md-3">
                    <span class="requisition_header">Generated By : </span><span class="requisition_text">{{@$data->created_by}}</span>
                </div>
                <div class="col-md-3">
                    <span class="requisition_header">Vendor : </span><span class="requisition_text">{{@$data->vendor}}</span>
                </div>
            </div>
            <hr>
            <div class="table-responsive">
                <table class="table table-striped card-table table-vcenter text-nowrap border">
                    <thead class="bg-primary text-white">
                        <tr>
                            <th class="text-white">#</th>
                            <th class="text-white">Item Name</th>
                            <th class="text-white">Batch No</th>
                            <th class="text-white">Exp. Date</th>
                            <th class="text-white">Quantity</th>
                            <th class="text-white">Test Qty</th>

                            <th class="text-white">Rate/Unit(₹)</th>
                            <th class="text-white">Discount(₹)</th>
                            <th class="text-white">Discount(%)</th>
                            <th class="text-white">MRP/Unit(₹)</th>
                            <th class="text-white">CGST %</th>
                            <th class="text-white">SGST %</th>
                            <th class="text-white">IGST %</th>
                            <th class="text-white">Total GST Amount(₹)</th>
                            <th class="text-white">Amount(₹)</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if((@$item_list) && $item_list != '')
                            @foreach($item_list as $item)
                            <tr>
                                <th scope="row">{{ $loop->iteration }}</th>
                                <td>{{@$item->item_name}}</td>
                                <td>{{@$item->part_no ? $item->part_no : "N/A"}}</td>
                                <td>{{@$item->exp_date ? date("d-m-Y", strtotime($item->exp_date)): "N/A"}}</td>
                                <td>{{@$item->unit_qty}} {{@$item->unit}} {{@$item->sub_unit_qty}} {{@$item->sub_unit}}</td>
                                <td>{{@$item->test_qty ? @$item->test_qty : '0'}}</td>
                                <td>{{@$item->rate}}</td>
                                <td>{{@$item->discount_amount}}</td>
                                <td>{{@$item->discount_percentage}}</td>
                                <td>{{@$item->mrp}}</td>
                                <td>{{@$item->cgst}}</td>
                                <td>{{@$item->sgst}}</td>
                                <td>{{@$item->igst}}</td>
                                <td>{{@$item->cgst_amount + @$item->sgst_amount + @$item->igst_amount}}</td>
                                <td>{{ number_format(@$item->amount, 2) }}</td>
                            </tr>
                            @endforeach
                        @endif
                    </tbody>
                </table>
                <hr>

                <div class="row">
                    <div class="col-md-5">
                        <label class="form-label">Note</label>
                        <textarea name="note" class="form-control" readonly>{{@$data->note}}</textarea>
                    </div>
                    <div class="col-md-3">
                        <label class="form-label">Payment Terms</label>
                        <input name="payment_terms" class="form-control" value="{{@$data->payment_terms}}" readonly />
                    </div>
                    <div class="col-md-4">
                        <div class="container my-5">
                            <div class="d-flex justify-content-end">
                                <span class="bilpo_name">Total(₹) </span><span class="bilpo_value"> : {{@$data->sub_total}}</span>
                            </div>
                            <div class="d-flex justify-content-end">
                                <span class="bilpo_name">Discount </span><span class="bilpo_value"> : {{@$data->discount_amount}} {{ @$data->discount_type == 'percentage' ? '%' : 'Rs' }}</span>
                            </div>
                            <div class="d-flex justify-content-end">
                                <span class="bilpo_name">Total CGST(₹) </span><span class="bilpo_value"> : {{@$data->total_cgst_amount}}</span>
                            </div>
                            <div class="d-flex justify-content-end">
                                <span class="bilpo_name">Total SGST(₹) </span><span class="bilpo_value"> : {{@$data->total_sgst_amount}}</span>
                            </div>
                            <div class="d-flex justify-content-end">
                                <span class="bilpo_name">Total IGST(₹) </span><span class="bilpo_value"> : {{@$data->total_igst_amount}}</span>
                            </div>

                            <div class="d-flex justify-content-end" style="color:#0101c5">
                                <span class="bilpo_name">Grand Amount(₹) </span><span class="bilpo_value"> : {{@$data->total}}</span>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js')
@endpush

