@extends('layouts.structure')
@push('title')
    <title>Purchase List</title>
@endpush
@push('css')
@endpush
@section('main-content')
<div class="row">
    <div class="col-lg-12 col-xl-12 col-md-12 col-sm-12">
        <div class="card">
            <div class="card-header card_hearder_mimi justify-content-between">
                <h4 class="card-title card_hearder_mimi_text">
                    Purchase List
                </h4>
                <div>
                   <span> <a class="btn btn-sm btn-warning" href="{{ route('optical.add-purchase') }}">ADD PURCHASE</a></span>                 </div>
            </div>
            <div class="card-body p-0" style="margin-bottom: 32px;">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-borderless text-nowrap data-table">
                            <thead></thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js')
<script type="text/javascript">
    $(function() {
        var table = $('.data-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('optical.listing-purchase') }}",
            columns: [
                {
                    data: null,
                    name: 'sl_no',
                    title: 'SN',
                    render: function (data, type, row, meta) {
                        return meta.row + meta.settings._iDisplayStart + 1;
                    },
                    orderable: false,
                    searchable: false
                },
                {
                    data: 'id',
                    name: 'id',
                    title: 'Purchase No.',
                    render: function (data, type, row, meta) {
                        return `P#${row.id}`;
                    },
                },
                {
                    data: 'invoice_no',
                    name: 'st_purchases.invoice_no',
                    title: 'Invoice No.',
                },
                {
                    data: 'po_id',
                    name: 'po_id',
                    title: 'Purchase Order No.',
                    render: function(data, type, row) {
                        return row.po_id ? `PO#${row.po_id}` : '';
                    },
                },
                {
                    data: 'vendor',
                    name: 'v.vendor_name',
                    title: 'Vendor',
                },
                {
                    data: 'created_by',
                    name: 'u.name',
                    title: 'Generated By',
                },
                {
                    data: 'date',
                    name: 'date',
                    title: 'Date',
                    render: function(data, type, row) {
                        return `${formatDateTime(row.date)}`;
                    },
                },
                {
                    data: 'purchase_info',
                    name: 'purchase_info',
                    title: 'Payment Terms',
                },
                {
                    data: 'action',
                    name: 'action',
                    title: 'Action',
                    searchable: true
                },
            ],
        });
    });
</script>
@endpush
