@extends('layouts.structure')
@push('title')
    <title>Requisition Details</title>
@endpush
@push('css')
@endpush
@section('main-content')
<div class="row">
    <div class="card">
        <div class="card-header d-block card_hearder_mimi">
            <div class="row">
                <div class="col-md-6 card-title card_hearder_mimi_text">
                   Requisition Details
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="col-md-12" style="float: left;">
                <div class="row">
                    <div class="col-md-4">
                        <span class="requisition_header">Requisition No : </span><span
                            class="requisition_text">R#{{@$data->id}}
                        </span>
                    </div>
                    <div class="col-md-4">
                        <span class="requisition_header">Requisition Date : </span><span
                            class="requisition_text">
                            {{dateFor($data->requisition_date, true)}}
                        </span>
                    </div>
                    <div class="col-md-4">
                        <span class="requisition_header">Generated By : </span><span
                            class="requisition_text">{{@$data->generated_by}}
                        </span>
                    </div>
                    <div class="col-md-4">
                        <span class="requisition_header">Note : </span><span class="requisition_text"
                            style="color:blue">{{@$data->note}}
                        </span>
                    </div>
                    <div class="col-md-4">
                        <span class="requisition_header">Department : </span><span class="requisition_text"
                            style="color:blue"> {{@$data->department }}
                        </span>
                    </div>
                    <div class="col-md-4">
                        {!! @$data->is_given == '0' ? '<span style="color :#c01e1e ;font-size: 18px; font-weight: 600;">Not issued</span>':'<span style="color:#158f34;font-size: 18px; font-weight: 600;">Issued</span>' !!}
                    </div>
                </div>

            </div>
            <div class="table-responsive mt-4">
                <table class="table table-striped card-table table-vcenter text-nowrap border">
                    <thead class="bg-primary text-white">
                        <tr class="border">
                            <th  class="text-white border">#</th>
                            <th  class="text-white border">Item Name</th>
                            <th  class="text-white border">Unit</th>
                            <th  class="text-white border">Sub-Unit</th>
                            <th  class="text-white border">Total</th>
                            <th  class="text-white border">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if(isset($item_list) && $item_list != '')
                            @foreach($item_list as $list)
                            <tr>
                                <th scope="row" class="border">{{ $loop->iteration }}</th>
                                <td class="border">{{$list->item_name}} </td>
                                <td class="border">{{$list->unit_qty}} {{$list->unit_name}}</td>
                                <td class="border">{{$list->sub_unit_qty}} {{$list->sub_unit_name}}</td>
                                <td class="border">{{$list->unit_qty * $list->sub_unit_no + $list->sub_unit_qty}} {{$list->sub_unit_name}}
                                    <small style="font-size: 10px">(1 {{$list->unit_name}} = {{$list->sub_unit_no}} {{$list->sub_unit_name}})</small></td>
                                <td class="border"> </td>
                            </tr>
                            @endforeach
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js')
@endpush

