<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Bill Report Export</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 0; padding: 20px; font-size: 12px; }
        h2 { text-align: center; margin-bottom: 5px; }
        .report-meta { text-align: center; margin-bottom: 15px; font-weight: 600; }
        table { width: 100%; border-collapse: collapse; font-size: 11px; table-layout: fixed; }
        th, td { border: 1px solid #444; padding: 6px 8px; text-align: center; word-break: break-word; }
        th { background: #0d6efd; color: #fff; }
        .left { text-align: left; }
    </style>
</head>
<body>
    <h2>Edit Bill Report</h2>
    <p class="report-meta">
        Period: {{ $filters['from_date'] ?? '-' }} to {{ $filters['to_date'] ?? '-' }}
    </p>
    <table>
        <thead>
            <tr>
                <th>SN</th>
                <th class="left">Patient (UHID)</th>
                <th>Bill No</th>
                <th>Section</th>
                <th>Update By/Date</th>
                <th>Generated By</th>
                <th>Bill Date</th>
                <th>Total</th>
                <th>Payment</th>
                <th>Due</th>
                <th>Credit</th>
                <th>Refund</th>
                <th>Adjustment</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($records as $index => $row)
                @php
                    $adj = 0;
                    if (!empty($row->cradituse_bill_amount)) {
                        $adj = array_sum(explode('_', trim($row->cradituse_bill_amount, '_')));
                    }
                @endphp
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td class="left">{{ $row->patient_name }} ({{ $row->patient_uhid ?? $row->patient_id }})</td>
                    <td>{{ $row->uid }}</td>
                    <td>{{ $row->section }}</td>
                    <td>{{ $row->edit_by_name }}<br>{{ dateFor($row->edit_at, true) }}</td>
                    <td>{{ $row->created_by_name }}</td>
                    <td>{{ dateFor($row->bill_date, true) }}</td>
                    <td>{{ $row->grand_total }}</td>
                    <td>{{ $row->total_payment }}</td>
                    <td>{{ $row->due_amount }}</td>
                    <td>{{ $row->cradit_amount }}</td>
                    <td>{{ $row->refund_amount }}</td>
                    <td>{{ $adj }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="13">No records found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
