@extends('layouts.structure')

@push('title')
    <title>{{ $title }} - {{ hospital('title') }}</title>
@endpush

@section('main-content')
    <div class="row">
        <div class="col-lg-12 col-xl-12 col-md-12 col-sm-12">
            <div class="card">
                <div class="card-header d-block card_hearder_mimi">
                    <div class="row">
                        <div class="col-md-6 card-title card_hearder_mimi_text">
                            Medicine Purchase List
                        </div>

                        <div class="col-md-6 text-right">
                            <div class="d-block">

                                <a href="{{ route('pharmacy.create-purchase') }}" class="btn btn-primary btn-sm"><i
                                        class="fa fa-tablets"></i>Create Purchase</a>

                            </div>
                        </div>
                    </div>
                </div>


                <div class="card-bodyp hospital_allcardbodydesign border" style="display:none" id="search_result">
                    <div class="table-responsive">
                        <table class="table table-hover card-table table-vcenter text-nowrap border"
                            style="background-color:#d9d9d9;border:1px solid black !important;    width: 50%;">
                            <thead class="text-white" style="background-color:#5e6545">
                                <tr class="border-left">
                                    <th class="text-white">Medicine Name</th>
                                </tr>
                            </thead>
                            <tbody id="search_result_row">

                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="card-body">
                    <div class="">
                        <div class="table-responsive">
                            <table class="table table-hover table-striped table-bordered data-table w-100">
                                <thead>

                                </thead>
                                <tbody>

                                </tbody>
                            </table>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <script type="text/javascript">
        $(function() {
            var table = $('.data-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('pharmacy.purchase-lists') }}",
                columns: [{
                        data: null,
                        name: 'sl_no',
                        title: 'Sl. No',
                        render: function(data, type, row, meta) {
                            return meta.row + meta.settings._iDisplayStart + 1;
                        },
                        orderable: false,
                        searchable: false
                    },
                    {
                        data: 'id',
                        name: 'id',
                        title: 'Purchase No',
                    },
                    {
                        data: 'total',
                        name: 'total',
                        title: 'Purchase Amount'
                    },
                    {
                        data: 'vendor_name',
                        name: 'med_purchases.vendor_name',
                        title: 'Vendor Name'
                    },
                    {
                        data: 'generated_by_name',
                        name: 'med_purchases.generated_by_name',
                        title: 'Generated By',
                        render: function(data, type, row) {
                            return row.generated_by_name ? row.generated_by_name :
                                '<span class="text-muted">Not Assigned</span>';
                        }
                    },
                    {
                        data: 'invoice_no',
                        name: 'invoice_no',
                        title: 'Invoice No'
                    },
                    {
                        data: 'date',
                        name: 'date',
                        title: 'Purchase Date',
                        // render: function(data, type, row) {
                        //     return `${formatDateTime(row.date)}`;
                        // },
                        // orderable: false,
                        // searchable: true
                    },
                    {
                        data: 'is_updated_in_stock',
                        name: 'is_updated_in_stock',
                        title: 'Stock Status',
                        render: function(data, type, row) {
                            if (data == '0') {
                                return '<span class="badge badge-danger">Stock Not Update</span>';
                            } else {
                                return '<span class="badge badge-primary">Stock Updated</span>';
                            }
                        }
                    },
                    {
                        data: 'action',
                        name: 'action',
                        title: 'Action'
                    },
                ],
                 rowCallback: function(row, data) {
                if (data.is_updated_in_stock == '0') {
                    $(row).css('background-color', '#FFB3B5');
                }else{
                    $(row).css('background-color', '#d3fdf7');
                }
            }
            });
        });
    </script>
@endpush
