<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bill List Export</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            font-size: 12px;
        }

        h2 {
            text-align: center;
            margin-bottom: 0;
        }

        .report-meta {
            text-align: center;
            margin-bottom: 20px;
            font-weight: 600;
        }

        table {
            width: 98%;
            border-collapse: collapse;
            margin-top: 10px;
            table-layout: fixed;
        }

        th,
        td {
            border: 1px solid #444;
            padding: 4px 6px;
            font-size: 10px;
            text-align: center;
            word-break: break-word;
            white-space: normal;
        }

        th {
            background: #0d6efd;
            color: #fff;
        }

        tbody tr:nth-child(even) {
            background: #f7f7f7;
        }

        .left {
            text-align: left;
        }
    </style>
</head>
<body>
    <h2>Bill List</h2>
    <p class="report-meta">
        Period: {{ $filters['from_date'] ?? '-' }} to {{ $filters['to_date'] ?? '-' }}
        @php
            $filterNameMap = [
                'p.name' => 'Patient Name',
                'p.uhid' => 'UHID',
                'p.phone' => 'Phone',
                'billings.uid' => 'Billing No',
                'billings.section' => 'Section',
            ];
            $fieldName = $filters['field_name'] ?? null;
            $fieldValue = $filters['field_value'] ?? null;
            $selectValue = $filters['select_value'] ?? null;
            $filterDisplay = null;
            if ($fieldName === 'billings.section' && $selectValue) {
                $filterDisplay = $filterNameMap[$fieldName] ?? ucfirst($fieldName) . ': ' . $selectValue;
            } elseif ($fieldName && $fieldValue) {
                $filterDisplay = $filterNameMap[$fieldName] ?? ucfirst($fieldName) . ': ' . $fieldValue;
            }
        @endphp
        @if ($filterDisplay)
            <br>Filter: {{ $filterDisplay }}
        @endif
    </p>

    <table>
        <thead>
            <tr>
                <th>SN</th>
                <th class="left">Patient (UHID)</th>
                <th>Phone</th>
                <th>Bill No</th>
                <th>Section</th>
                <th>Date &amp; Time</th>
                <th>Total (₹)</th>
                <th>Payment (₹)</th>
                <th>Due (₹)</th>
                <th>Refund (₹)</th>
                <th>Generated By</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($records as $index => $row)

                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td class="left">{{ strtoupper($row->patient_name) }} ({{ $row->patient_uhid ?? $row->patient_id }})</td>
                    <td>{{ $row->phone }}</td>
                    <td>{{ $row->uid }}</td>
                    <td>{{ $row->section }}</td>
                    <td>{{ dateFor($row->bill_date, true) }}</td>
                    <td>{{ number_format($row->grand_total ?? 0, 2) }}</td>
                    <td>{{ number_format($row->total_payment ?? 0, 2) }}</td>
                    <td>{{ number_format($row->due_amount ?? 0, 2) }}</td>
                    <td>{{ number_format($row->refund_amount ?? 0, 2) }}</td>
                    <td>{{ $row->created_name ?? '-' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="10">No records found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
