@extends('layouts.structure')
@push('title')
    <title>Edit Bill Report</title>
@endpush
@push('css')
@endpush
@section('main-content')
<div class="row">
    <div class="col-lg-12 col-xl-12 col-md-12 col-sm-12">
        <div class="card">
            <div class="card-header card_hearder_mimi justify-content-between">
                <h4 class="card-title card_hearder_mimi_text">EDIT BILL REPORT</h4>
            </div>
            <div class="">
                <div class="">
                    <form method="POST" id="filterForm">
                        @csrf
                        <div class="whitebackground">
                        <div class="row">
                            <div class="col-sm-2">
                                <div class="form-group">
                                    <input type="text" value="" class="form-control datePickr" id="fromDate" name="from_date" placeholder="Choose From Date">
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group">
                                    <input type="text" value="" class="form-control datePickr" id="toDate" name="to_date" placeholder="Choose To Date">
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group d-flex">
                                    <button type="submit" class="btn btn-primary px-3 mr-2"><i
                                        class="fas fa-filter"></i> Filter</button>
                                    <button type="button" class="btn btn-success px-3 mr-2" id="todayBtn"><i
                                        class="fas fa-calendar-week"></i> Today</button>
                                    <button type="button" class="btn btn-warning px-3" id="resetBtn"><i
                                        class="fas fa-history"></i> Reset</button>
                                </div>
                            </div>
                        </div>
                        </div>
                    </form>
                </div>
                <div class="whitebackground">
                <div class="table-responsive" id="table-responsive">
                    <table class="table table-bordered data-table">
                        <thead></thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js')
<script type="text/javascript">
    var table;
    $('#filterForm').on('submit', function(e) {
        e.preventDefault();
        table.draw();
    });
    $('#todayBtn').on('click', function () {
        const today = moment().format('DD-MM-YYYY');
        $('#fromDate').val(today);
        $('#toDate').val(today);
        table.draw();
    });
    $('#resetBtn').on('click', function () {
        // Clear all filters
        $('#fromDate').val('');
        $('#toDate').val('');

        // Redraw the DataTable (will trigger serverSide AJAX reload)
        table.draw();
    });

    $(function() {
        table = $('.data-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: {
                url: "{{ route('reports.edit-bill') }}",
                data: function(d) {
                    d.from_date = $('#fromDate').val();
                    d.to_date = $('#toDate').val();
                }
            },
            columns: [
                {
                    data: null,
                    name: 'sl_no',
                    title: 'SN',
                    render: function (data, type, row, meta) {
                        return meta.row + meta.settings._iDisplayStart + 1;
                    },
                    orderable: false,
                    searchable: false
                },
                {
                    data: 'patient',
                    name: 'p.name',
                    title: 'Patient',
                },
                {
                    data: 'billing',
                    name: 'billings.uid',
                    title: 'Bill No',
                },
                {
                    data: 'section',
                    name: 'billings.section',
                    title: 'Section',
                },
                {
                    data: 'edit_date',
                    name: 'u1.name',
                    title: 'Update By/Date',
                },
                {
                    data: 'created_by_name',
                    name: 'u2.name',
                    title: 'Generated By',
                },
                {
                    data: 'bill_date',
                    name: 'billings.bill_date',
                    title: 'Date & Time',
                },
                {
                    data: 'amount',
                    name: 'billings.total_payment',
                    title: 'Amount (₹)',
                },
                {
                    data: 'refund',
                    name: 'billings.refund_amount',
                    title: 'Refund/Adjustment',
                },
                {
                    data: 'action',
                    name: 'billings.refund_amount',
                    title: 'Action',
                },
            ],
            rowCallback: function(row, data) {
                if(data.bill_status == 3){
                    $(row).css('background-color', '#eabbbb');
                }else{
                    if(data.due_amount > 0){
                        $(row).css('background-color', '#ffff9b');
                    }else{
                        $(row).css('background-color', '#d3fdf7');
                    }
                }
            }
        });
    });
</script>
@endpush
