@extends('layouts.structure')
@push('title')
    <title>Expense Details</title>
@endpush
@push('css')
@endpush
@section('main-content')
<div class="row">
    <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center card_hearder_mimi">
            <div class="card-title card_hearder_mimi_text">
                Expense Details
            </div>
        </div>
        <div class="card-body">
            <div class="col-md-12" style="float: left;">
                <div class="row">
                    <div class="col-md-4">
                        <span class="requisition_header">Expense No : </span><span
                            class="requisition_text">EXP#{{@$data->id}}
                        </span>
                    </div>
                    <div class="col-md-4">
                        <span class="requisition_header">Exoense Date : </span><span
                            class="requisition_text">
                            {{dateFor($data->expense_date, true)}}
                        </span>
                    </div>
                    <div class="col-md-4">
                        <span class="requisition_header">Generated By : </span><span
                            class="requisition_text">{{ @$data->created_by }}
                        </span>
                    </div>
                    <div class="col-md-4">
                        <span class="requisition_header">Requisition No : </span><span class="requisition_text"
                            style="color:blue">R#{{ @$data->requisition_id }}
                        </span>
                    </div>
                    <div class="col-md-4">
                        <span class="requisition_header">Department : </span><span class="requisition_text"
                            style="color:blue"> {{@$data->department_name }}
                        </span>
                    </div>
                </div>

            </div>
            <div class="table-responsive mt-4">
                <table class="table table-striped card-table table-vcenter text-nowrap border">
                    <thead class="bg-primary text-white">
                        <tr class="border">
                            <th class="text-white border">#</th>
                            <th class="text-white border">Item Name</th>
                            <th class="text-white border">Unit Name</th>
                            <th class="text-white border">Unit QTY</th>
                            <th class="text-white border">Sub-Unit Name</th>
                            <th class="text-white border">Sub-Unit QTY</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if(isset($item_list) && $item_list != '')
                            @foreach($item_list as $list)
                            <tr>
                                <th scope="row" class="border">{{ $loop->iteration }}</th>
                                <td class="border">{{ $list->item_name }} </td>
                                <td class="border">{{ $list->unit_name }}</td>
                                <td class="border">{{ $list->unit_qty }}</td>
                                <td class="border">{{ $list->sub_unit_name }}</td>
                                <td class="border">{{ $list->sub_unit_qty }}</td>
                            </tr>
                            @endforeach
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js')
@endpush

