@extends('layouts.structure')
@push('title')
    <title>Item Issue List</title>
@endpush
@push('css')
@endpush
@section('main-content')
<div class="row">
    <div class="col-lg-12 col-xl-12 col-md-12 col-sm-12">
        <div class="card">
            <div class="card-header card_hearder_mimi justify-content-between">
                <h4 class="card-title card_hearder_mimi_text">
                    Item Issue List
                </h4>
                <div><a class="btn btn-sm btn-warning" href="{{ route('store.add-item-issue') }}">ADD ITEM ISSUE</a></div>
            </div>
            <div class="card-body p-0" style="margin-bottom: 32px;">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-borderless text-nowrap data-table">
                            <thead></thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js')
<script type="text/javascript">
    $(function() {
        var table = $('.data-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('store.listing-item-issue') }}",
            columns: [
                {
                    data: null,
                    name: 'sl_no',
                    title: 'SN',
                    render: function (data, type, row, meta) {
                        return meta.row + meta.settings._iDisplayStart + 1;
                    },
                    orderable: false,
                    searchable: false
                },
                {
                    data: 'id',
                    name: 'id',
                    title: 'Issue No.',
                },
                {
                    data: 'requisition_id',
                    name: 'requisition_id',
                    title: 'Requisition No.',
                },
                {
                    data: 'department_name',
                    name: 'd.department_name',
                    title: 'Issue To',
                },
                {
                    data: 'created_by',
                    name: 'u.name',
                    title: 'Generated By',
                },
                {
                    data: 'date',
                    name: 'date',
                    title: 'Date',
                    render: function(data, type, row) {
                        return `${formatDateTime(row.date)}`;
                    },
                },

                {
                    data: 'action',
                    name: 'action',
                    title: 'Action',
                    searchable: true
                },
            ],
        });
    });
</script>
@endpush
