@extends('layouts.structure')
@push('title')
    <title>Issue Details</title>
@endpush
@push('css')
@endpush
@section('main-content')
<div class="row">
    <div class="card">
        <div class="card-header d-block card_hearder_mimi">
            <div class="row">
                <div class="col-md-6 card-title card_hearder_mimi_text">
                    Issue Details
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                    <span class="requisition_header"><i class="fas fa-yin-yang text-danger"></i> Issue No : </span><span
                        class="requisition_text">{{@$data->id}}
                    </span>
                </div>
                <div class="col-md-4">
                    <span class="requisition_header"><i class="fas fa-yin-yang text-danger"></i> Issue Date : </span><span
                        class="requisition_text">
                        {{dateFor($data->date, true)}}
                    </span>
                </div>
                <div class="col-md-4">
                    <span class="requisition_header"><i class="fas fa-yin-yang text-danger"></i> Issue Department : </span><span
                        class="requisition_text">{{@$data->department_name}}
                    </span>
                </div>
                <div class="col-md-4">
                    <span class="requisition_header"><i class="fas fa-yin-yang text-danger"></i> Requisition ID : </span><span class="requisition_text"
                        style="color:blue">{{@$data->requisition_id}}
                    </span>
                </div>
                <div class="col-md-4">
                    <span class="requisition_header"><i class="fas fa-yin-yang text-danger"></i> Generated By : </span><span class="requisition_text"
                        style="color:blue"> {{@$data->created_by }}
                    </span>
                </div>
            </div>
            <hr>
            <div class="table-responsive">
                <table class="table table-striped card-table table-vcenter text-nowrap border">
                    <thead class="bg-primary text-white">
                        <tr>
                            <th class="text-white">#</th>
                            <th class="text-white">Item Name</th>
                            <th class="text-white">Batch No.</th>
                            <th class="text-white">Exp. Date</th>
                            <th class="text-white">Quantity</th>
                            <th class="text-white">Amount (₹)</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(@$item_list ?? [] as $item)
                        <tr>
                            <th scope="row">{{ $loop->iteration }}</th>
                            <td>{{@$item->item_name}}</td>
                            <td>{{@$item->part_no ? $item->part_no : "N/A"}}</td>
                            <td>{{@$item->exp_date ? dateFor($item->exp_date) : "N/A"}}</td>
                            <td>{{@$item->unit_qty}} {{@$item->unit}} {{@$item->sub_unit_qty}} {{@$item->sub_unit}}</td>
                            <td>{{ number_format(@$item->amount, 2) }}</td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                <hr>

                <div class="row">
                    <div class="col-md-6">
                        @if(@$data->note)
                        <label class="form-label">Note</label>
                        <textarea name="note" class="form-control" readonly>{{@$data->note}}</textarea>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js')
@endpush

