@extends('layouts.structure')
@push('title')
    <title>Purchase Order List</title>
@endpush
@push('css')
@endpush
@section('main-content')
<div class="row">
    <div class="col-lg-12 col-xl-12 col-md-12 col-sm-12">
        <div class="card">
            <div class="card-header card_hearder_mimi justify-content-between">
                <h4 class="card-title card_hearder_mimi_text">
                    Purchase Order List
                </h4>
            </div>
            <div class="card-body p-0" style="margin-bottom: 32px;">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-borderless text-nowrap data-table">
                            <thead></thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js')
<script type="text/javascript">
    $(function() {
        var table = $('.data-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('store.listing-purchase-order-verify') }}",
            columns: [
                {
                    data: null,
                    name: 'sl_no',
                    title: 'SN',
                    render: function (data, type, row, meta) {
                        return meta.row + meta.settings._iDisplayStart + 1;
                    },
                    orderable: false,
                    searchable: false
                },
                {
                    data: 'st_purchase_orders.fy_po_no',
                    name: 'st_purchase_orders.fy_po_no',
                    title: 'Purchase Order No.',
                    render: function (data, type, row, meta) {
                        return `KGH/${row.fy_po_no}`;
                    },
                },
                {
                    data: 'requisition_links',
                    name: 'st_purchase_orders.requisition_ids',
                    title: 'Requisition',
                    orderable: false,
                },
                {
                    data: 'vendor',
                    name: 'v.vendor_name',
                    title: 'Vendor',
                },
                {
                    data: 'created_by',
                    name: 'u.name',
                    title: 'Generated By',
                },
                {
                    data: 'status_badge',
                    name: 'st_purchase_orders.status',
                    title: 'Status',
                },
                {
                    data: 'po_date',
                    name: 'po_date',
                    title: 'Date',
                    render: function(data, type, row) {
                        return `${formatDateTime(row.po_date)}`;
                    },
                },
                {
                    data: 'action',
                    name: 'action',
                    title: 'Action',
                    searchable: true
                },
            ],
        });
    });
</script>
@endpush
