@extends('layouts.structure')
@push('title')
    <title>Requisition List</title>
@endpush
@push('css')
@endpush
@section('main-content')
<div class="row">
    <div class="col-lg-12 col-xl-12 col-md-12 col-sm-12">
        <div class="card">
            <div class="card-header card_hearder_mimi justify-content-between">
                <h4 class="card-title card_hearder_mimi_text">
                    Requisition List
                </h4>
                <div>
                    <a class="btn btn-sm btn-warning" href="{{Route('store.add-requisition')}}">ADD REQUISITION</a>
                    <div class="btn-group btn-group-sm ml-2" role="group" aria-label="download requisitions">
                        <a target="_blank" class="btn btn-outline-primary" href="{{ route('store.requisition-pdf', ['filter' => 'pending']) }}">
                            <i class="fa fa-file-pdf"></i> Created</a>
                        <a target="_blank" class="btn btn-outline-info" href="{{ route('store.requisition-pdf', ['filter' => 'verified']) }}">
                            <i class="fa fa-file-pdf"></i> Verified</a>
                        <a target="_blank" class="btn btn-outline-success" href="{{ route('store.requisition-pdf', ['filter' => 'approved']) }}">
                            <i class="fa fa-file-pdf"></i> Approved</a>
                        <a target="_blank" class="btn btn-outline-dark" href="{{ route('store.requisition-pdf', ['filter' => 'others']) }}">
                            <i class="fa fa-file-pdf"></i> Others</a>
                    </div>
                </div>
            </div>
            <div class="card-body p-0" style="margin-bottom: 32px;">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-borderless text-nowrap data-table">
                            <thead></thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js')
<script type="text/javascript">
    $(function() {
        var table = $('.data-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('store.listing-requisition') }}",
            columns: [
                {
                    data: null,
                    name: 'sl_no',
                    title: 'SN',
                    render: function (data, type, row, meta) {
                        return meta.row + meta.settings._iDisplayStart + 1;
                    },
                    orderable: false,
                    searchable: false
                },
                {
                    data: 'id',
                    name: 'id',
                    title: 'Requisition No.',
                    render: function (data, type, row, meta) {
                        return `R#${row.id}`;
                    },
                },
                {
                    data: 'generated_by',
                    name: 'u.name',
                    title: 'Generated By',
                },
                {
                    data: 'department',
                    name: 'd.department_name',
                    title: 'Department',
                },
                {
                    data: 'requisition_date',
                    name: 'requisition_date',
                    title: 'Date',
                    render: function(data, type, row) {
                        return `${formatDateTime(row.requisition_date)}`;
                    },
                },
                {
                    data: 'status',
                    name: 'status',
                    title: 'Status',
                },
                {
                    data: 'action',
                    name: 'action',
                    title: 'Action',
                    searchable: true
                },
            ],
        });
    });
</script>
@endpush
