@extends('layouts.structure')
@push('title')
    <title>Requisition Details</title>
@endpush
@push('css')
@endpush

@section('main-content')
<div class="row">
    <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center card_hearder_mimi">
            <div class="card-title card_hearder_mimi_text">
                Requisition Details
            </div>
            @if( in_array(@$data->is_given, [1,2]) && @$type == 'approve' )
                <a href="{{ route('store.requisition-details', [ed($data->id, true), 'approve', 1]) }}" class="btn btn-primary px-5">Approve</a>
            @endif
        </div>

        <div class="card-body">
            <div class="col-md-12" style="float: left;">
                <div class="row">
                    <div class="col-md-4">
                        <span class="requisition_header">Requisition No : </span>
                        <span class="requisition_text">R#{{@$data->id}}</span>
                    </div>
                    <div class="col-md-4">
                        <span class="requisition_header">Requisition Date : </span>
                        <span class="requisition_text">{{ dateFor($data->requisition_date, true) }}</span>
                    </div>
                    <div class="col-md-4">
                        <span class="requisition_header">Generated By : </span>
                        <span class="requisition_text">{{ @$data->generated_by }}</span>
                    </div>
                    <div class="col-md-4">
                        <span class="requisition_header">Note : </span>
                        <span class="requisition_text" style="color:blue">{{ @$data->note }}</span>
                    </div>
                    <div class="col-md-4">
                        <span class="requisition_header">Department : </span>
                        <span class="requisition_text" style="color:blue">{{ @$data->department }}</span>
                    </div>
                    <div class="col-md-4">
                        <span class="requisition_header">Verified By : </span>
                        <span class="requisition_text">{{ @$data->verified_by_name ?: '-' }}</span>
                    </div>
                    <div class="col-md-4">
                        <span class="requisition_header">Approved By : </span>
                        <span class="requisition_text">{{ @$data->approved_by_name ?: '-' }}</span>
                    </div>
                    <div class="col-md-4">
                        <span class="requisition_header">Rejected By : </span>
                        <span class="requisition_text">{{ @$data->reject_by_name ?: '-' }}</span>
                    </div>
                    <div class="col-md-4">
                        <span class="requisition_header">Rejected Note : </span>
                        <span class="requisition_text" style="color:red">{{ @$data->reject_note ?: '-' }}</span>
                    </div>
                    <div class="col-md-4">
                        <span class="requisition_header">Status : </span>
                        @if($data->is_given == 1 && $data->created_by)
                            <span class="badge badge-warning" style="font-size:1rem; padding:0.5em 0.75em;">Pending</span>
                        @elseif($data->is_given == 0 && $data->approved_by)
                            <span class="badge badge-info" style="font-size:1rem; padding:0.5em 0.75em;">Approved</span>
                        @elseif($data->is_given == 2 && $data->verified_by)
                            <span class="badge badge-primary" style="font-size:1rem; padding:0.5em 0.75em;">Verified</span>
                        @elseif($data->is_given == 3 && $data->edit_by)
                            <span class="badge badge-danger" style="font-size:1rem; padding:0.5em 0.75em;">Rejected</span>
                        @elseif($data->is_given == 4)
                            <span class="badge badge-success" style="font-size:1rem; padding:0.5em 0.75em;">Issued</span>
                        @elseif($data->is_given == 5)
                            <span class="badge badge-light" style="font-size:1rem; padding:0.5em 0.75em;">Received</span>
                        @endif
                    </div>
                </div>
            </div>

            <div class="table-responsive mt-4">
                <table class="table table-striped card-table table-vcenter text-nowrap border">
                    <thead class="bg-primary text-white">
                        <tr class="border">
                            <th class="text-white border">#</th>
                            <th class="text-white border">Item Name</th>
                            <th class="text-white border">Unit</th>
                            <th class="text-white border">Sub-Unit</th>
                            <th class="text-white border">Total</th>
                            <th class="text-white border">Unit Price</th>
                            <th class="text-white border">Total Price</th>
                        </tr>
                    </thead>

                    @php $grand_total = 0; @endphp

                    <tbody>
                        @if(isset($item_list) && $item_list != '')
                            @foreach($item_list as $list)
                                @php
                                    $grand_total += (float) ($list->total_price ?? 0);
                                @endphp
                                <tr>
                                    <th scope="row" class="border">{{ $loop->iteration }}</th>
                                    <td class="border">{{ $list->item_name }}</td>
                                    <td class="border">{{ $list->unit_qty }} {{ $list->unit_name }}</td>
                                    <td class="border">{{ $list->sub_unit_qty }} {{ $list->sub_unit_name }}</td>
                                    <td class="border">
                                        {{ ($list->unit_qty * $list->sub_unit_no) + $list->sub_unit_qty }} {{ $list->sub_unit_name }}
                                        <small style="font-size: 10px">(1 {{ $list->unit_name }} = {{ $list->sub_unit_no }} {{ $list->sub_unit_name }})</small>
                                    </td>
                                    <td class="border">{{ number_format((float)($list->item_unit_price ?? 0), 2) }}</td>
                                    <td class="border">{{ number_format((float)($list->total_price ?? 0), 2) }}</td>
                                </tr>
                            @endforeach
                        @endif
                    </tbody>

                    <tfoot>
                        <tr>
                            <th colspan="6" class="text-right border">Grand Total</th>
                            <th class="border">{{ number_format($grand_total, 2) }}</th>
                        </tr>
                    </tfoot>
                </table>
            </div>

        </div>
    </div>
</div>
@endsection

@push('js')
@endpush
