<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Requisition List</title>
    <style>
        @page {
            size: A4 landscape;
            margin: 10mm 15mm;
        }

        body {
            font-family: 'Segoe UI', sans-serif;
            color: #1a1a1a;
            margin: 0;
            background: #fff;
        }

        .container {
            width: 100%;
            padding: 10px;
        }

        .header img {
            width: 320px;
            max-width: 45%;
        }

        .header {
            text-align: center;
            margin-bottom: 10px;
        }

        .page-title {
            text-align: center;
            margin-bottom: 4px;
        }

        .page-meta {
            text-align: center;
            font-size: 11px;
            margin-bottom: 20px;
            color: #555;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 12px;
        }

        table th,
        table td {
            border: 1px solid #444;
            padding: 6px 8px;
        }

        table th {
            background: #ebf0ff;
            text-align: left;
        }

        .status-pill {
            display: inline-block;
            padding: 2px 8px;
            border-radius: 12px;
            background: #f0f0f0;
            font-size: 11px;
            color: #141414;
        }

        .footer {
            margin-top: 15px;
            font-size: 11px;
            display: flex;
            justify-content: space-between;
        }
    </style>
</head>
<body>
    <div class="container">
        {{-- @if(!empty($header_image_path))
            <div class="header">
                <img src="{{ 'file:///' . $header_image_path }}" alt="Company Logo">
            </div>
        @endif --}}
        <div class="page-title">
            <h2>Requisition List</h2>
            <div class="page-meta">{{ $filterLabel }}</div>
            <div class="page-meta">Printed at: {{ dateFor(now(), true) }}</div>
        </div>
        @php
            $statusLabels = [
                0 => 'Approved',
                1 => 'Pending',
                2 => 'Verified',
                3 => 'Rejected',
                4 => 'Issued',
                5 => 'Issue Received',
                6 => 'Expense Received',
            ];
        @endphp
        <table>
            <thead>
                <tr>
                    <th style="width: 4%;">SN</th>
                    <th style="width: 11%;">Requisition No</th>
                    <th style="width: 14%;">Generated By</th>
                    <th style="width: 11%;">Department</th>
                    <th style="width: 12%;">Date</th>
                    <th style="width: 13%;">Status</th>
                </tr>
            </thead>
            <tbody>
                @forelse($requisitions as $requisition)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                         <td>
                            @if($requisition->department_code)
                                {{ $requisition->department_code }}#{{ $requisition->vid ?? $requisition->id }}
                            @else
                                R#{{ $requisition->vid ?? $requisition->id }}
                            @endif
                        </td>
                        <td>{{ $requisition->generated_by ?? '-' }}</td>
                        <td>{{ $requisition->department ?? '-' }}</td>
                        <td>{{ dateFor($requisition->requisition_date, true) }}</td>
                        <td>
                            <span class="status-pill">{{ $statusLabels[$requisition->is_given] ?? 'Unknown' }}</span>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="8" style="text-align: center; font-style: italic;">No requisitions found for this filter.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>
        <div class="footer">
            <span>Prepared by: {{ Auth::user()->name ?? 'System' }}</span>
            <span>Date: {{ dateFor(now(), true) }}</span>
        </div>
    </div>
</body>
</html>
