<!DOCTYPE html>
<html>
<title>Eexpence</title>
<meta charset="utf-8">

<head>
    <link href="{{ asset('public/assets/plugins/datatable/css/buttons.bootstrap4.min.css') }}" rel="stylesheet">
    <link href="{{ asset('public/assets/plugins/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('public/assets/css/icons.css') }}" rel="stylesheet" />
</head>

<body>

    <style>
        @page {
            size: A4 portrait;
            margin: 0;
            padding: 0;
        }

        @media print {

            html,
            body {
                width: 25cm;
                margin: 0 !important;
                padding: 5 !important;
                overflow: hidden;
                font-family: 'verdana';
            }
        }

        body {
            font-family: sans-serif;
            background: #ffffff;
            margin: 0 auto;
            width: 100%;
        }

        table {
            background-position: center;
            background-repeat: no-repeat;
        }

        tr {
            width: 100%;
            height: auto;
        }

        @media print {
            #printButton {
                display: none;
            }
        }
    </style>

    <div style="padding: 0px 7px 30px 120px;width: 93%;">
        <div style="margin: 10px 0px 0px 503px" id="printButton">
            <button class="btn btn-primary btn-sm" onclick="printpage()"><i class="fa fa-print"></i>Print</button>
            <a href="{{ $back }}" class="btn btn-danger btn-sm"><i class="fa fa-times"></i>Close</a>
        </div>
        <!-- ==========================================code here================================== -->
        <table style="width: 100%;border-collapse: collapse">
            <tr style="text-align: center;">
                <td>
                    <img src="{{ asset('public/assets/images/header') }}/{{ $header_image->logo }}"
                        alt="logo" style="width: 80%;">
                </td>
            </tr>
        </table>

        <table style="width: 97%; border-collapse: collapse;margin-top: 1%;margin: 10px 0px 10px 13px;">
            <tbody>
                <tr>
                    <td colspan="2" style="text-align: center;font-size: 19px; font-weight: bold; color:#0072b7">
                        <b>Expense</b>
                    </td>
                </tr>
            </tbody>
        </table>

        <!-- Requisition Details Table -->
        <table style="width:100%; border-collapse:collapse; margin-bottom:15px; border:1px solid #000; font-size:13px;">
            <tbody>
                <tr>
                    <td style="width:33%; padding:6px; border:1px solid #000;">
                        <b>Expense No :</b> EXP#{{ @$data->id }}
                    </td>
                    <td style="width:33%; padding:6px; border:1px solid #000;">
                        <b>Expense Date :</b> {{ dateFor($data->expense_date, true) }}
                    </td>
                    <td style="width:34%; padding:6px; border:1px solid #000;">
                        <b>Generated By :</b> {{ @$data->created_by }}
                    </td>
                </tr>
                <tr>
                    <td style="width:33%; padding:6px; border:1px solid #000;">
                        <b>Department :</b> <span style="color:blue">{{ @$data->department_name }}</span>
                    </td>
                </tr>
            </tbody>
        </table>

        <!-- Item List Table -->
        <table style="width:100%; border-collapse:collapse; margin-top:20px; font-size:13px; border:1px solid #000;">
            <thead>
                <tr style="background:#007bff; color:#fff;">
                    <th style="padding:8px; border:1px solid #000; width:5%;">#</th>
                    <th style="padding:8px; border:1px solid #000; width:10%;">Item Name</th>
                    <th style="padding:8px; border:1px solid #000; width:10%;">Unit Name</th>
                    <th style="padding:8px; border:1px solid #000; width:10%;">Unit QTY</th>
                    <th style="padding:8px; border:1px solid #000; width:10%;">Sub-Unit Name</th>
                    <th style="padding:8px; border:1px solid #000; width:10%;">Sub-Unit QTY</th>
                </tr>
            </thead>
            <tbody>
                @if(isset($item_list) && $item_list != '')
                    @foreach($item_list as $list)
                    <tr>
                        <td style="padding:6px; border:1px solid #000;">{{ $loop->iteration }}</td>
                        <td style="padding:6px; border:1px solid #000;">{{ $list->item_name }}</td>
                        <td style="padding:6px; border:1px solid #000;">{{ $list->unit_name }}</td>
                        <td style="padding:6px; border:1px solid #000;">{{ $list->unit_qty }}</td>
                        <td style="padding:6px; border:1px solid #000;">{{ $list->sub_unit_name }}</td>
                        <td style="padding:6px; border:1px solid #000;">{{ $list->sub_unit_qty }}</td>
                    </tr>
                    @endforeach
                @endif
            </tbody>
        </table>

        <span style="padding:10px 25px;line-height: 20px;font-weight:500;font-size:11px;float: left;">PREPARED BY: {{ Auth::user()->name }}</span>
        <span style="padding:10px 30px;line-height: 20px;font-weight:500;font-size:11px;float: right;">Date: {{ dateFor(date('d-m-Y h:i:s'), true) }}</span>

    </div>
</body>
<script>
    function printpage() {
        window.print();
    }
</script>

</html>
