<!DOCTYPE html>
<html>
<title>Daily Eexpence</title>
<meta charset="utf-8">

<head>
    <link href="{{ asset('public/assets/plugins/datatable/css/buttons.bootstrap4.min.css') }}" rel="stylesheet">
    <link href="{{ asset('public/assets/plugins/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('public/assets/css/icons.css') }}" rel="stylesheet" />
</head>

<body>

    <style>
        @page {
            size: A4 portrait;
            margin: 0;
            padding: 0;
        }

        @media print {

            html,
            body {
                width: 25cm;
                margin: 0 !important;
                padding: 5 !important;
                overflow: hidden;
                font-family: 'verdana';
            }
        }

        body {
            font-family: sans-serif;
            background: #ffffff;
            margin: 0 auto;
            width: 100%;
        }

        table {
            background-position: center;
            background-repeat: no-repeat;
        }

        tr {
            width: 100%;
            height: auto;
        }

        @media print {
            #printButton {
                display: none;
            }
        }
    </style>

    <div style="padding: 0px 7px 30px 50px;width: 93%;">
        <div style="margin: 10px 0px 0px 503px" id="printButton">
            <button class="btn btn-primary btn-sm" onclick="printpage()"><i class="fa fa-print"></i>Print</button>
            <a href="{{ $back }}" class="btn btn-danger btn-sm"><i class="fa fa-times"></i>Close</a>
        </div>
        <!-- ==========================================code here================================== -->
        <table style="width: 100%;border-collapse: collapse">
            <tr style="text-align: center;">
                <td>
                    <img src="{{ asset('public/assets/images/header') }}/{{ $header_image->logo }}"
                        alt="logo" style="width: 80%;">
                </td>
            </tr>
        </table>

        <table style="width: 97%; border-collapse: collapse;margin-top: 1%;margin: 10px 0px 10px 13px;">
            <tbody>
                <tr>
                    <td colspan="2" style="text-align: center;font-size: 19px; font-weight: bold; color:#0072b7">
                        <b>Purchase</b>
                    </td>
                </tr>
            </tbody>
        </table>

        <!-- Purchase Details Table -->
        <table style="width:100%; border-collapse:collapse; margin-bottom:15px; border:1px solid #000; font-size:13px;">
            <tbody>
                <tr>
                    <td style="width:25%; padding:6px; border:1px solid #000;">
                        <b>Purchase No. :</b> P#{{ @$data->id }} <small>({{ ucfirst(@$data->type) }} Purchase)</small>
                    </td>
                    <td style="width:25%; padding:6px; border:1px solid #000;">
                        <b>Purchase Date :</b> {{ dateFor($data->date, true) }}
                    </td>
                    <td style="width:25%; padding:6px; border:1px solid #000;">
                        <b>Generated By :</b> {{ @$data->created_by }}
                    </td>
                    <td style="width:25%; padding:6px; border:1px solid #000;">
                        <b>Vendor :</b> {{ @$data->vendor }}
                    </td>
                </tr>
            </tbody>
        </table>


        <!-- Purchase Items Table -->
        <table style="width:100%; border-collapse:collapse; margin-top:15px; font-size:12px; border:1px solid #000;">
            <thead>
                <tr style="background:#007bff; color:#fff; text-align:center;">
                    <th style="border:1px solid #000; padding:6px;">#</th>
                    <th style="border:1px solid #000; padding:6px;">Item Name</th>
                    <th style="border:1px solid #000; padding:6px;">Batch No</th>
                    <th style="border:1px solid #000; padding:6px;">Exp. Date</th>
                    <th style="border:1px solid #000; padding:6px;">Quantity</th>
                    <th style="border:1px solid #000; padding:6px;">Test Qty</th>
                    <th style="border:1px solid #000; padding:6px;">Rate/Unit(₹)</th>
                    <th style="border:1px solid #000; padding:6px;">Discount(₹)</th>
                    <th style="border:1px solid #000; padding:6px;">Discount(%)</th>
                    <th style="border:1px solid #000; padding:6px;">MRP/Unit(₹)</th>
                    <th style="border:1px solid #000; padding:6px;">CGST %</th>
                    <th style="border:1px solid #000; padding:6px;">SGST %</th>
                    <th style="border:1px solid #000; padding:6px;">IGST %</th>
                    <th style="border:1px solid #000; padding:6px;">Total GST Amount(₹)</th>
                    <th style="border:1px solid #000; padding:6px;">Amount(₹)</th>
                </tr>
            </thead>
            <tbody>
                @if((@$item_list) && $item_list != '')
                    @foreach($item_list as $item)
                    <tr style="text-align:center;">
                        <td style="border:1px solid #000; padding:5px;">{{ $loop->iteration }}</td>
                        <td style="border:1px solid #000; padding:5px; text-align:left;">{{ @$item->item_name }}</td>
                        <td style="border:1px solid #000; padding:5px;">{{ @$item->part_no ? $item->part_no : "N/A" }}</td>
                        <td style="border:1px solid #000; padding:5px;">{{ @$item->exp_date ? date("d-m-Y", strtotime($item->exp_date)) : "N/A" }}</td>
                        <td style="border:1px solid #000; padding:5px;">{{ @$item->unit_qty }} {{ @$item->unit }} {{ @$item->sub_unit_qty }} {{ @$item->sub_unit }}</td>
                        <td style="border:1px solid #000; padding:5px;">{{ @$item->test_qty ? @$item->test_qty : '0' }}</td>
                        <td style="border:1px solid #000; padding:5px;">{{ @$item->rate }}</td>
                        <td style="border:1px solid #000; padding:5px;">{{ @$item->discount_amount }}</td>
                        <td style="border:1px solid #000; padding:5px;">{{ @$item->discount_percentage }}</td>
                        <td style="border:1px solid #000; padding:5px;">{{ @$item->mrp }}</td>
                        <td style="border:1px solid #000; padding:5px;">{{ @$item->cgst }}</td>
                        <td style="border:1px solid #000; padding:5px;">{{ @$item->sgst }}</td>
                        <td style="border:1px solid #000; padding:5px;">{{ @$item->igst }}</td>
                        <td style="border:1px solid #000; padding:5px;">{{ @$item->cgst_amount + @$item->sgst_amount + @$item->igst_amount }}</td>
                        <td style="border:1px solid #000; padding:5px;">{{ number_format(@$item->amount, 2) }}</td>
                    </tr>
                    @endforeach
                @endif
            </tbody>
        </table>

        <!-- Notes and Summary -->
        <table style="width:100%; border-collapse:collapse; margin-top:15px; font-size:13px;">
            <tr>
                <td style="width:45%; vertical-align:top; padding:8px; border:1px solid #000;">
                    <b>Note:</b><br>
                    @if(@$data->note)
                        <div style="border:1px solid #ccc; padding:6px; min-height:60px; font-size:12px;">
                            {{ @$data->note }}
                        </div>
                    @endif
                </td>
                <td style="width:25%; vertical-align:top; padding:8px; border:1px solid #000;">
                    <b>Payment Terms:</b><br>
                    <div style="border:1px solid #ccc; padding:6px; min-height:30px; font-size:12px;">
                        {{ @$data->payment_terms }}
                    </div>
                    <br>
                    GRN Status : {{ ($data->status == 1) ? 'Completed' : 'Incomplete' }}
                </td>
                <td style="width:30%; vertical-align:top; padding:8px; border:1px solid #000;">
                    <table style="width:100%; font-size:12px; border-collapse:collapse;">
                        <tr>
                            <td style="padding:4px; text-align:right;">Total (₹)</td>
                            <td style="padding:4px; text-align:right;">: {{ @$data->sub_total }}</td>
                        </tr>
                        <tr>
                            <td style="padding:4px; text-align:right;">Discount</td>
                            <td style="padding:4px; text-align:right;">: {{ @$data->discount_amount }} {{ @$data->discount_type == 'percentage' ? '%' : 'Rs' }}</td>
                        </tr>
                        <tr>
                            <td style="padding:4px; text-align:right;">Total CGST (₹)</td>
                            <td style="padding:4px; text-align:right;">: {{ @$data->total_cgst_amount }}</td>
                        </tr>
                        <tr>
                            <td style="padding:4px; text-align:right;">Total SGST (₹)</td>
                            <td style="padding:4px; text-align:right;">: {{ @$data->total_sgst_amount }}</td>
                        </tr>
                        <tr>
                            <td style="padding:4px; text-align:right;">Total IGST (₹)</td>
                            <td style="padding:4px; text-align:right;">: {{ @$data->total_igst_amount }}</td>
                        </tr>
                        <tr style="color:#0101c5; font-weight:bold;">
                            <td style="padding:6px; text-align:right;">Grand Amount (₹)</td>
                            <td style="padding:6px; text-align:right;">: {{ @$data->total }}</td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>


        <span style="padding:10px 25px;line-height: 20px;font-weight:500;font-size:11px;float: left;">PREPARED BY: {{ Auth::user()->name }}</span>
        <span style="padding:10px 30px;line-height: 20px;font-weight:500;font-size:11px;float: right;">Date: {{ dateFor(date('d-m-Y h:i:s'), true) }}</span>

    </div>
</body>
<script>
    function printpage() {
        window.print();
    }
</script>

</html>
