<!DOCTYPE html>
<html>
<title>Issue Item</title>
<meta charset="utf-8">

<head>
    <link href="{{ asset('public/assets/plugins/datatable/css/buttons.bootstrap4.min.css') }}" rel="stylesheet">
    <link href="{{ asset('public/assets/plugins/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('public/assets/css/icons.css') }}" rel="stylesheet" />
</head>

<body>

    <style>
        @page {
            size: A4 portrait;
            margin: 0;
            padding: 0;
        }

        @media print {

            html,
            body {
                width: 25cm;
                margin: 0 !important;
                padding: 5 !important;
                overflow: hidden;
                font-family: 'verdana';
            }
        }

        body {
            font-family: sans-serif;
            background: #ffffff;
            margin: 0 auto;
            width: 100%;
        }

        table {
            background-position: center;
            background-repeat: no-repeat;
        }

        tr {
            width: 100%;
            height: auto;
        }

        @media print {
            #printButton {
                display: none;
            }
        }
    </style>

    <div style="padding: 0px 7px 30px 110px;width: 93%;">
        <div style="margin: 10px 0px 0px 503px" id="printButton">
            <button class="btn btn-primary btn-sm" onclick="printpage()"><i class="fa fa-print"></i>Print</button>
            <a href="{{ $back }}" class="btn btn-danger btn-sm"><i class="fa fa-times"></i>Close</a>
        </div>
        <!-- ==========================================code here================================== -->
        <table style="width: 100%;border-collapse: collapse">
            <tr style="text-align: center;">
                <td>
                    <img src="{{ asset('public/assets/images/header') }}/{{ $header_image->logo }}"
                        alt="logo" style="width: 80%;">
                </td>
            </tr>
        </table>

        <table style="width: 97%; border-collapse: collapse;margin-top: 1%;margin: 10px 0px 10px 13px;">
            <tbody>
                <tr>
                    <td colspan="2" style="text-align: center;font-size: 19px; font-weight: bold; color:#0072b7">
                        <b>Item Issue</b>
                    </td>
                </tr>
            </tbody>
        </table>

        <!-- Issue Details Table -->
        <table style="width:100%; border-collapse:collapse; margin-bottom:15px; border:1px solid #000;">
            <tbody>
                <tr>
                    <td style="width:33%; padding:6px; font-size:13px; border:1px solid #000;">
                        <b><i class="fas fa-yin-yang" style="color:red;"></i> Issue No :</b>
                        {{ @$data->id }}
                    </td>
                    <td style="width:33%; padding:6px; font-size:13px; border:1px solid #000;">
                        <b><i class="fas fa-yin-yang" style="color:red;"></i> Issue Date :</b>
                        {{ dateFor($data->date, true) }}
                    </td>
                    <td style="width:34%; padding:6px; font-size:13px; border:1px solid #000;">
                        <b><i class="fas fa-yin-yang" style="color:red;"></i> Issue Department :</b>
                        {{ @$data->department_name }}
                    </td>
                </tr>
                <tr>
                    <td style="width:33%; padding:6px; font-size:13px; border:1px solid #000;">
                        <b><i class="fas fa-yin-yang" style="color:red;"></i> Requisition ID :</b>
                        <span style="color:blue">{{ @$data->requisition_id }}</span>
                    </td>
                    <td style="width:33%; padding:6px; font-size:13px; border:1px solid #000;">
                        <b><i class="fas fa-yin-yang" style="color:red;"></i> Generated By :</b>
                        <span style="color:blue">{{ @$data->created_by }}</span>
                    </td>
                    <td style="width:34%; padding:6px; font-size:13px; border:1px solid #000;">
                        <b><i class="fas fa-yin-yang" style="color:red;"></i> Status :</b>
                        {{ ($data->status == 1) ? 'Issued' : 'Not Issue' }}
                    </td>
                </tr>
            </tbody>
        </table>

        <!-- Issue Details Table -->
        <table style="width:100%; border-collapse:collapse; margin-top:15px; border:1px solid #000;">
            <thead>
                <tr style="background:#007bff; color:#fff; text-align:center;">
                    <th style="width:5%; padding:8px; border:1px solid #000; font-size:13px;">#</th>
                    <th style="width:25%; padding:8px; border:1px solid #000; font-size:13px;">Item Name</th>
                    <th style="width:15%; padding:8px; border:1px solid #000; font-size:13px;">Batch No.</th>
                    <th style="width:15%; padding:8px; border:1px solid #000; font-size:13px;">Exp. Date</th>
                    <th style="width:20%; padding:8px; border:1px solid #000; font-size:13px;">Quantity</th>
                    <th style="width:20%; padding:8px; border:1px solid #000; font-size:13px;">Amount (₹)</th>
                </tr>
            </thead>
            <tbody>
                @foreach(@$item_list ?? [] as $item)
                <tr>
                    <td style="text-align:center; padding:6px; font-size:12px; border:1px solid #000;">
                        {{ $loop->iteration }}
                    </td>
                    <td style="text-align:left; padding:6px; font-size:12px; border:1px solid #000;">
                        {{ @$item->item_name }}
                    </td>
                    <td style="text-align:center; padding:6px; font-size:12px; border:1px solid #000;">
                        {{ @$item->part_no ? $item->part_no : "N/A" }}
                    </td>
                    <td style="text-align:center; padding:6px; font-size:12px; border:1px solid #000;">
                        {{ @$item->exp_date ? dateFor($item->exp_date) : "N/A" }}
                    </td>
                    <td style="text-align:center; padding:6px; font-size:12px; border:1px solid #000;">
                        {{ @$item->unit_qty }} {{ @$item->unit }} {{ @$item->sub_unit_qty }} {{ @$item->sub_unit }}
                    </td>
                    <td style="text-align:center; padding:6px; font-size:12px; border:1px solid #000;">
                        {{ number_format(@$item->amount, 2) }}
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <span style="padding:10px 25px;line-height: 20px;font-weight:500;font-size:11px;float: left;">PREPARED BY: {{ Auth::user()->name }}</span>
        <span style="padding:10px 30px;line-height: 20px;font-weight:500;font-size:11px;float: right;">Date: {{ dateFor(date('d-m-Y h:i:s'), true) }}</span>

    </div>
</body>
<script>
    function printpage() {
        window.print();
    }
</script>

</html>
