@extends('layouts.structure')
@push('title')
    <title>Expenses List</title>
@endpush
@push('css')
@endpush
@section('main-content')
<div class="row">
    <div class="col-lg-12 col-xl-12 col-md-12 col-sm-12">
        <div class="card">
            <div class="card-header card_hearder_mimi justify-content-between">
                <h4 class="card-title card_hearder_mimi_text">
                    Expenses List
                </h4>
                <div><a class="btn btn-sm btn-warning" href="{{ route('kt.add-daily-expenses') }}">ADD EXPENSES</a></div>
            </div>
            <div class="card-header d-block">
                <form method="POST" id="filterForm">
                    @csrf
                    <div class="whitebackground">
                        <div class="row">
                            <div class="col-sm-2">
                                <div class="form-group">
                                    <input type="text" value="" class="form-control datePickr"
                                        id="fromDate" name="from_date" placeholder="Choose From Date">
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group">
                                    <input type="text" value="" class="form-control datePickr"
                                        id="toDate" name="to_date" placeholder="Choose To Date">
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group d-flex">
                                    <button type="submit" class="btn btn-primary px-3 mr-2"><i
                                            class="fas fa-filter"></i> Filter</button>
                                    <button type="button" class="btn btn-warning px-3" id="resetBtn"><i
                                            class="fas fa-history"></i> Reset</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="card-body p-0" style="margin-bottom: 32px;">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover table-striped table-bordered data-table w-100">
                            <thead></thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js')
<script type="text/javascript">
    var table;
    $('#filterForm').on('submit', function(e) {
        e.preventDefault();
        table.draw();
    });
    $('#todayBtn').on('click', function() {
        const today = moment().format('DD-MM-YYYY');
        $('#fromDate').val(today);
        $('#toDate').val(today);
        table.draw();
    });
    $('#resetBtn').on('click', function() {
        // Clear all filters
        $('#fromDate').val('');
        $('#toDate').val('');

        // Redraw the DataTable (will trigger serverSide AJAX reload)
        table.draw();
    });
    $(function() {
        table = $('.data-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: {
                url: "{{ route('kt.daily-expenses') }}",
                data: function(d) {
                    d.from_date = $('#fromDate').val();
                    d.to_date = $('#toDate').val();
                }
            },
            columns: [
                {
                    data: null,
                    name: 'sl_no',
                    title: 'SN',
                    render: function (data, type, row, meta) {
                        return meta.row + meta.settings._iDisplayStart + 1;
                    },
                    orderable: false,
                    searchable: false
                },
                {
                    data: 'id',
                    name: 'id',
                    title: 'Expenses No.',
                    render: function(data, type, row) {
                        return `KTE#${row.id}`;
                    },
                },
                {
                    data: 'date',
                    name: 'date',
                    title: 'Date',
                    render: function(data, type, row) {
                        return `${formatDateTime(row.date,'date')}`;
                    },
                },
                {
                    data: 'total_meal',
                    name: 'kt_expenses.total_meal',
                    title: 'Approximate Meal',
                },
                {
                    data: 'created_by',
                    name: 'u.name',
                    title: 'Generated By',
                },
                {
                    data: 'status',
                    name: 'status',
                    title: 'Status',
                    searchable: false
                },
                {
                    data: 'action',
                    name: 'action',
                    title: 'Action',
                    searchable: false
                },
            ],
        });
    });
</script>
@endpush
