@extends('layouts.structure')
@push('title')
    <title>Expenses Details</title>
@endpush
@push('css')
@endpush
@section('main-content')
<div class="row">
    <div class="card">
        <div class="card-header d-block card_hearder_mimi">
            <div class="row">
                <div class="col-md-6 card-title card_hearder_mimi_text">
                    Expenses Details
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-3">
                    <span class="requisition_header"><i class="fas fa-yin-yang text-danger"></i> Expenses No : </span><span
                        class="requisition_text">KTE#{{@$data->id}}
                    </span>
                </div>
                <div class="col-md-3">
                    <span class="requisition_header"><i class="fas fa-yin-yang text-danger"></i> Expenses Date : </span><span
                        class="requisition_text">
                        {{dateFor($data->date, true)}}
                    </span>
                </div>
                <div class="col-md-3">
                    <span class="requisition_header"><i class="fas fa-yin-yang text-danger"></i> Approximate Meal : </span><span
                        class="requisition_text">{{@$data->total_meal}}
                    </span>
                </div>
                <div class="col-md-3">
                    <span class="requisition_header"><i class="fas fa-yin-yang text-danger"></i> Generated By : </span><span class="requisition_text"
                        style="color:blue"> {{@$data->created_by }}
                    </span>
                </div>
                <div class="col-md-6">
                    <span class="requisition_header"><i class="fas fa-yin-yang text-danger"></i> Note : </span><span class="requisition_text"
                        style="color:blue"> {{@$data->note}}
                    </span>
                </div>
            </div>
            <hr>
            <div class="table-responsive">
                <table class="table table-striped card-table table-vcenter text-nowrap border">
                    <thead class="bg-primary text-white">
                        <tr>
                            <th class="text-white">#</th>
                            <th class="text-white">Item Name</th>
                            <th class="text-white">Quantity</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(@$item_list ?? [] as $item)
                        <tr>
                            <th scope="row">{{ $loop->iteration }}</th>
                            <td>{{@$item->item_name}}</td>
                            <td>{{@$item->unit_qty}} {{@$item->unit}}</td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js')
@endpush

