@extends('layouts.structure')
@push('title')
    <title>Purchase Details</title>
@endpush
@push('css')
@endpush
@section('main-content')
<div class="row">
    <div class="card">
        <div class="card-header d-block card_hearder_mimi">
            <div class="row">
                <div class="col-md-6 card-title card_hearder_mimi_text">
                    Purchase Details
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-3">
                    <span class="requisition_header">Purchase No. : </span><span class="requisition_text">KTP#{{ @$data->id }}</span>
                </div>
                <div class="col-md-3">
                    <span class="requisition_header">Purchase Date : </span><span class="requisition_text">{{ date('d-m-Y h:i A', strtotime(@$data->date)) }}</span>
                </div>
                <div class="col-md-3">
                    <span class="requisition_header">Generated By : </span><span class="requisition_text">{{@$data->created_by}}</span>
                </div>
                <div class="col-md-3">
                    <span class="requisition_header">Vendor : </span><span class="requisition_text">{{@$data->supplier}}</span>
                </div>
                <div class="col-md-3">
                    <span class="requisition_header">PO ID : </span><span class="requisition_text">{{@$data->po_id ? 'KTPO#'.$data->po_id : ''}}</span>
                </div>
                <div class="col-md-3">
                    <span class="requisition_header">Payment Terms : </span><span class="requisition_text">{{@$data->payment_terms}}</span>
                </div>
                <div class="col-md-6">
                    <span class="requisition_header">Note : </span><span class="requisition_text">{{@$data->note}}</span>
                </div>
            </div>
            <hr>
            <div class="table-responsive">
                <table class="table table-striped card-table table-vcenter text-nowrap border">
                    <thead class="bg-primary text-white">
                        <tr>
                            <th class="text-white">#</th>
                            <th class="text-white">Item Name</th>
                            <th class="text-white">Exp. Date</th>
                            <th class="text-white">Quantity</th>
                            <th class="text-white">MRP/Unit(₹)</th>
                            <th class="text-white">Rate/Unit(₹)</th>
                            <th class="text-white">Net Amount(₹)</th>
                            <th class="text-white">Discount(₹)</th>
                            <th class="text-white">Discount(%)</th>
                            <th class="text-white">GST</th>
                            <th class="text-white">Amount(₹)</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if((@$item_list) && $item_list != '')
                            @foreach($item_list as $item)
                            <tr>
                                <th scope="row">{{ $loop->iteration }}</th>
                                <td>{{@$item->item_name}}</td>
                                <td>{{@$item->exp_date ? date("d-m-Y", strtotime($item->exp_date)): "N/A"}}</td>
                                <td>{{@$item->unit_qty}} {{@$item->unit}}</td>
                                <td>{{@$item->mrp}}</td>
                                <td>{{@$item->rate}}</td>
                                <td>{{@$item->net_amount}}</td>
                                <td>{{@$item->discount_amount}}</td>
                                <td>{{@$item->discount_percentage}}</td>
                                <td>{{@$item->gst_amount ?? 0}} {{@$item->gst ? '('.$item->gst.'%)' : ''}}</td>
                                <td>{{ number_format(@$item->amount, 2) }}</td>
                            </tr>
                            @endforeach
                        @endif
                    </tbody>
                </table>
                <hr>

                <div class="row justify-content-end">
                    <div class="col-md-4">
                        <div class="container my-5">
                            <div class="d-flex justify-content-end">
                                <span class="bilpo_name">Total(₹) </span><span class="bilpo_value"> : {{@$data->sub_total}}</span>
                            </div>
                            <div class="d-flex justify-content-end">
                                <span class="bilpo_name">Discount(₹) </span><span class="bilpo_value"> : {!! @$data->discount_value ? '<small>('.$data->discount_value.($data->discount_type == 'percentage' ? '%' : '₹').')</small>' : '' !!} {{@$data->discount_amount}}</span>
                            </div>
                            <div class="d-flex justify-content-end">
                                <span class="bilpo_name">Total GST(₹) </span><span class="bilpo_value"> : {{@$data->total_gst_amount}}</span>
                            </div>

                            <div class="d-flex justify-content-end" style="color:#0101c5">
                                <span class="bilpo_name">Grand Amount(₹) </span><span class="bilpo_value"> : {{@$data->total}}</span>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js')
@endpush

